In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
arr = np.random.randint(25)

In [9]:
arr

10

In [10]:
arr = np.arange(25)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
arr.max()

24

In [14]:
arr.min()

0

In [15]:
arr.argmax()

24

In [16]:
arr.argmin()

0

In [17]:
import numpy as np

In [18]:
arr = np.arange(0,11)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr[8]

8

In [21]:
arr[1:5]

array([1, 2, 3, 4])

In [22]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [23]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [24]:
arr[0:5] = 100

In [25]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [26]:
arr[:]= 99

In [27]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [28]:
arr_copy = arr.copy()

In [29]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [30]:
arr[0:5] = 99
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [31]:
arr = np.arange(0,11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[0:5] = 99

In [34]:
arr


array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [35]:
 import numpy as np

In [36]:
arr_2d = np.array([[5,10,5],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10,  5],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr_2d[0]

array([ 5, 10,  5])

In [38]:
arr_2d[1][1]

25

In [39]:
arr_2d [1,2]

30

In [40]:
arr = np.arange(1,11)

In [41]:
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [43]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [44]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [45]:
arr_2d[1,2]

12

In [46]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [47]:
arr = np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
#check scipy.org universal function
arr  + arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [50]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [52]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [53]:
arr/arr

/tmp/ipykernel_107654/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [54]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [55]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [56]:
arr.exp(arr)

AttributeError: 'numpy.ndarray' object has no attribute 'exp'

In [ ]:
np.exp(arr)

In [ ]:
np.max(arr)